spring:
  application:
    name: Lucky
  datasource:
    name: Location
    url: jdbc:mysql://120.79.21.18:3306/knowledge?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=true
    username: root
    password: pioneerbnxd8888..*..
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        enable_lazy_load_no_trans: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update